--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: active_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.active_sessions (
    id bigint NOT NULL,
    browser character varying(255),
    city character varying(255),
    country character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    device character varying(255),
    expired boolean NOT NULL,
    ip character varying(255) NOT NULL,
    last_request_at timestamp(6) with time zone NOT NULL,
    os character varying(255),
    provider_ip character varying(255),
    session_id character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: active_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.active_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.active_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_tag (
    article_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: article_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_translations (
    id bigint NOT NULL,
    alt_cover character varying(255) NOT NULL,
    blocks_json text NOT NULL,
    language character varying(255) NOT NULL,
    seo_description character varying(255) NOT NULL,
    seo_title character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    article_id bigint NOT NULL,
    CONSTRAINT article_translations_language_check CHECK (((language)::text = ANY ((ARRAY['RU'::character varying, 'UZ'::character varying])::text[])))
);


--
-- Name: article_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    comment_count integer NOT NULL,
    comments_enabled boolean NOT NULL,
    cover_name character varying(255) NOT NULL,
    cover_position character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    slug character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count bigint NOT NULL,
    CONSTRAINT articles_category_check CHECK (((category)::text = ANY ((ARRAY['NEWS'::character varying, 'ARTICLES'::character varying, 'PROBLEMS'::character varying, 'IDEAS'::character varying])::text[])))
);


--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment (
    id bigint NOT NULL,
    article_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    text text NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);





--
-- Name: login_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.login_attempts (
    id bigint NOT NULL,
    attempts integer NOT NULL,
    block_level integer,
    blocked_until timestamp(6) without time zone,
    ip character varying(255) NOT NULL,
    last_attempt timestamp(6) without time zone NOT NULL,
    username character varying(255)
);


--
-- Name: login_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.login_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: login_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.login_events (
    id bigint NOT NULL,
    asn bigint,
    browser character varying(255),
    city character varying(255),
    country character varying(255),
    created_at timestamp(6) without time zone,
    device character varying(255),
    ip character varying(255) NOT NULL,
    os character varying(255),
    provider character varying(255),
    provider_ip character varying(255),
    success boolean NOT NULL,
    user_agent character varying(512),
    username character varying(255),
    CONSTRAINT login_events_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[])))
);


--
-- Name: login_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.login_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persons (
    id bigint NOT NULL,
    alt character varying(255) NOT NULL,
    birth_date date NOT NULL,
    birth_place character varying(255) NOT NULL,
    death_age_years integer,
    death_date date,
    external_url character varying(255),
    image_filename character varying(255) NOT NULL,
    ru_description oid,
    ru_name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    sport_status character varying(255),
    sport_type character varying(255),
    type character varying(255) NOT NULL,
    uz_description oid,
    uz_name character varying(255) NOT NULL,
    zodiac character varying(255) NOT NULL,
    CONSTRAINT persons_birth_place_check CHECK (((birth_place)::text = ANY ((ARRAY['TASHKENT'::character varying, 'KARAKALPAKSTAN'::character varying, 'ANDIJAN'::character varying, 'BUKHARA'::character varying, 'FERGANA'::character varying, 'JIZZAKH'::character varying, 'KHOREZM'::character varying, 'NAMANGAN'::character varying, 'NAVOI'::character varying, 'KASHKADARYA'::character varying, 'SAMARKAND'::character varying, 'SURKHANDARYA'::character varying, 'SYRDARYA'::character varying])::text[]))),
    CONSTRAINT persons_sport_status_check CHECK (((sport_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'RETIRED'::character varying])::text[]))),
    CONSTRAINT persons_sport_type_check CHECK (((sport_type)::text = ANY ((ARRAY['FOOTBALL'::character varying, 'BOXING'::character varying, 'CHESS'::character varying, 'MMA'::character varying, 'WRESTLING'::character varying, 'TAEKWONDO'::character varying, 'WEIGHTLIFTING'::character varying, 'GYMNASTICS_ARTISTIC'::character varying, 'GYMNASTICS_RHYTHMIC'::character varying, 'TENNIS'::character varying, 'BASKETBALL'::character varying])::text[]))),
    CONSTRAINT persons_type_check CHECK (((type)::text = ANY ((ARRAY['SCIENTIST'::character varying, 'RELIGIOUS_FIGURE'::character varying, 'MILITARY_COMMANDER'::character varying, 'POET'::character varying, 'WRITER'::character varying, 'POLITICIAN'::character varying, 'ACTOR'::character varying, 'SINGER'::character varying, 'COMEDIAN'::character varying, 'ATHLETE'::character varying])::text[]))),
    CONSTRAINT persons_zodiac_check CHECK (((zodiac)::text = ANY ((ARRAY['ARIES'::character varying, 'TAURUS'::character varying, 'GEMINI'::character varying, 'CANCER'::character varying, 'LEO'::character varying, 'VIRGO'::character varying, 'LIBRA'::character varying, 'SCORPIO'::character varying, 'SAGITTARIUS'::character varying, 'CAPRICORN'::character varying, 'AQUARIUS'::character varying, 'PISCES'::character varying])::text[])))
);


--
-- Name: persons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);






--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    language character varying(255),
    name character varying(255) NOT NULL,
    CONSTRAINT tags_language_check CHECK (((language)::text = ANY ((ARRAY['RU'::character varying, 'UZ'::character varying])::text[])))
);


--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: two_factor_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.two_factor_attempts (
    id bigint NOT NULL,
    failures integer NOT NULL,
    locked_until timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(100) NOT NULL
);


--
-- Name: two_factor_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.two_factor_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.two_factor_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_favorite_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_favorite_articles (
    id bigint NOT NULL,
    article_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: user_favorite_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_favorite_articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_favorite_articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_filename character varying(255),
    blocked boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_name character varying(255),
    email character varying(255),
    password character varying(255),
    provider character varying(255),
    role character varying(255),
    two_factor_enabled boolean NOT NULL,
    two_factor_secret character varying(255),
    username character varying(255) NOT NULL,
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: active_sessions active_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_sessions
    ADD CONSTRAINT active_sessions_pkey PRIMARY KEY (id);


--
-- Name: article_tag article_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag
    ADD CONSTRAINT article_tag_pkey PRIMARY KEY (article_id, tag_id);


--
-- Name: article_translations article_translations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_translations
    ADD CONSTRAINT article_translations_pkey PRIMARY KEY (id);


--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--

--
-- Name: persons ix_person_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT ix_person_slug UNIQUE (slug);


--
-- Name: login_attempts login_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.login_attempts
    ADD CONSTRAINT login_attempts_pkey PRIMARY KEY (id);


--
-- Name: login_events login_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.login_events
    ADD CONSTRAINT login_events_pkey PRIMARY KEY (id);


--
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (id);




--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: two_factor_attempts two_factor_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.two_factor_attempts
    ADD CONSTRAINT two_factor_attempts_pkey PRIMARY KEY (id);


--
-- Name: login_attempts uk1aj87h0pyqe5joo8nem69fs95; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.login_attempts
    ADD CONSTRAINT uk1aj87h0pyqe5joo8nem69fs95 UNIQUE (ip, username);




--
-- Name: user_favorite_articles ukdolt9myllqh2b24x83wdvjsdm; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite_articles
    ADD CONSTRAINT ukdolt9myllqh2b24x83wdvjsdm UNIQUE (user_id, article_id);


--
-- Name: tags uke1swiml007fqv8v0n5gkp18se; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT uke1swiml007fqv8v0n5gkp18se UNIQUE (code, language);


--
-- Name: active_sessions ukew5ywef9a34md117p2c52ddut; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_sessions
    ADD CONSTRAINT ukew5ywef9a34md117p2c52ddut UNIQUE (session_id);


--
-- Name: tags ukjg3xm6htq0sg4voplnjhuksv5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT ukjg3xm6htq0sg4voplnjhuksv5 UNIQUE (name, language);


--
-- Name: two_factor_attempts ukjuh2hsx02lc2db4o8xagvl11l; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.two_factor_attempts
    ADD CONSTRAINT ukjuh2hsx02lc2db4o8xagvl11l UNIQUE (username);


--
-- Name: article_translations uknjowafucvuupxirf460r8meaj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_translations
    ADD CONSTRAINT uknjowafucvuupxirf460r8meaj UNIQUE (article_id, language);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: articles uksn7al9fwhgtf98rvn8nxhjt4f; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT uksn7al9fwhgtf98rvn8nxhjt4f UNIQUE (slug);


--
-- Name: user_favorite_articles user_favorite_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_favorite_articles
    ADD CONSTRAINT user_favorite_articles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



--
-- Name: idx_fav_article; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fav_article ON public.user_favorite_articles USING btree (article_id);


--
-- Name: idx_fav_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fav_user ON public.user_favorite_articles USING btree (user_id);


--
-- Name: idx_login_event_browser; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_browser ON public.login_events USING btree (browser);


--
-- Name: idx_login_event_city; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_city ON public.login_events USING btree (city);


--
-- Name: idx_login_event_country; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_country ON public.login_events USING btree (country);


--
-- Name: idx_login_event_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_created ON public.login_events USING btree (created_at);


--
-- Name: idx_login_event_created_success; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_created_success ON public.login_events USING btree (created_at, success);


--
-- Name: idx_login_event_device; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_device ON public.login_events USING btree (device);


--
-- Name: idx_login_event_ip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_ip ON public.login_events USING btree (ip);


--
-- Name: idx_login_event_ip_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_ip_created ON public.login_events USING btree (ip, created_at);


--
-- Name: idx_login_event_os; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_os ON public.login_events USING btree (os);


--
-- Name: idx_login_event_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_username ON public.login_events USING btree (username);


--
-- Name: idx_login_event_username_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_event_username_created ON public.login_events USING btree (username, created_at);


--
-- Name: idx_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_id ON public.active_sessions USING btree (session_id);


--
-- Name: idx_user_expired; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_expired ON public.active_sessions USING btree (user_id, expired);


--
-- Name: ix_person_birth_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_person_birth_date ON public.persons USING btree (birth_date);


--
-- Name: ix_person_birth_place; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_person_birth_place ON public.persons USING btree (birth_place);


--
-- Name: ix_person_death_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_person_death_date ON public.persons USING btree (death_date);


--
-- Name: ix_person_sport; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_person_sport ON public.persons USING btree (sport_type);


--
-- Name: ix_person_sport_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_person_sport_status ON public.persons USING btree (sport_status);


--
-- Name: ix_person_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_person_type ON public.persons USING btree (type);


--
-- Name: ix_person_zodiac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_person_zodiac ON public.persons USING btree (zodiac);


--
-- Name: article_tag fk3nvn435qf5rn1e9ph51e3r55h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag
    ADD CONSTRAINT fk3nvn435qf5rn1e9ph51e3r55h FOREIGN KEY (tag_id) REFERENCES public.tags(id);



--
-- Name: active_sessions fki160hxodalwko5kwgd80oeyq8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.active_sessions
    ADD CONSTRAINT fki160hxodalwko5kwgd80oeyq8 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: article_translations fklb0kl16sn4gu5f1ksy1rj77ci; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_translations
    ADD CONSTRAINT fklb0kl16sn4gu5f1ksy1rj77ci FOREIGN KEY (article_id) REFERENCES public.articles(id);


--
-- Name: article_tag fkmaj67sy3t0aqlsa99r5iubav4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_tag
    ADD CONSTRAINT fkmaj67sy3t0aqlsa99r5iubav4 FOREIGN KEY (article_id) REFERENCES public.article_translations(id);


--
-- Name: comment fkqm52p1v3o13hy268he0wcngr5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkqm52p1v3o13hy268he0wcngr5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

